name: Build, Publish and Release

on:
  push:
    branches: [ main ]

jobs:
  Build And Publish:
    name: 🎉 Build And Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Login to GitHub Packages
      - uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Set Env Variables
        run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
          echo "REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Build Docker image (multi-platform with Buildx)
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO }}/${{ env.REPO_NAME }}:latest
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64

  Release:
    runs-on: ubuntu-latest
    name: 🚀 Release
    needs: Build And Publish
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Archive build artifacts
        run: |
          tar -czvf build.tar.gz ./build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          body: |
            To know more about this release, please refer to the README.
          draft: false
          prerelease: false
          files: ./build.tar.gz