name: Build and Publish (Cache with actions/cache@v3)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Login to GitHub Packages
      - uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Restore cache
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.docker/cache
          key: ${{ runner.os }}-docker-${{ github.repository }}-build
          restore-keys: |
            ${{ runner.os }}-docker-${{ github.repository }}-build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: |  # Driver options
            image=moby/buildkit:master
          platforms: linux/amd64,linux/arm64  # Platforms to build for

      # Build Docker image (multi-platform with Buildx)
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/$(basename ${{ github.repository }}):latest

      # Save cache
      - name: Save cache
        uses: actions/cache@v3
        with:
          path: ~/.docker/cache
          key: ${{ runner.os }}-docker-${{ github.repository }}-build
          push-keys: |
            ${{ runner.os }}-docker-${{ github.repository }}-build
