name: Build and Publish (Cache with actions/cache@v3)

on:
  push:
    branches: [ main ]  # You can adjust the branch to trigger the build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Login to GitHub Packages
      - uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Restore cache (optional)
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.docker/cache  # Path to the cache directory
          key: ${{ runner.os }}-docker-${{ github.repository }}-build  # Unique cache key
          restore-keys: |   # List of cache keys to restore from
            ${{ runner.os }}-docker-${{ github.repository }}-build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container  # Default driver, can be omitted
          driver-opts: |  # Driver options (specifying Buildkit image)
            image=moby/buildkit:master
          platforms: linux/amd64,linux/arm64  # Platforms to build for

      # Build Docker image (multi-platform with Buildx)
      - name: Build and push Docker image
        run: |
          # Set environment variable for image repository (lowercase)
          echo ::set-env name=IMAGE_REPOSITORY::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

          # Build and push Docker image
          docker build --push . -t ghcr.io/$IMAGE_REPOSITORY/linktobio-maker:v1.0.0


      # Save cache (optional)
      - name: Save cache
        uses: actions/cache@v3
        with:
          path: ~/.docker/cache  # Path to the cache directory
          key: ${{ runner.os }}-docker-${{ github.repository }}-build  # Unique cache key
          push-keys: |   # List of cache keys to save
            ${{ runner.os }}-docker-${{ github.repository }}-build
